### PR TITLE
Anagrams

### PR DESCRIPTION
**Pull request by t00f**
A simple exercise that can be done during a 45min onsite interview.

### CODE REVIEW

**Comment by primalmotion** [comment]
I think the goal is is to give the exercise as is to the candidate. We should not add any info on how we judge the candidate, and the text should be addressed to the interviewee not the interviewer

**Comment by t00f** [comment]
That's why there are two files:
* Instructions.md which is the one we give to the candidate
* AporetoIntructions.md which is instructions for the Aporeto interviewer

**Comment by Dogild** [comment]
It's why there is an Instructions file and an AporetoInstructions file

**Comment by primalmotion** [comment]
ok so we can't simply git clone this repo on the laptop and let the guy alone for 3h

**Comment by t00f** [comment]
No. It's our resource center. 
We don't want to git clone and let the guy have all our exercises as well :)

He will be here for the github challenge and then, we will ask some onsite interview as well. So not possible to clone this repo

**Comment by primalmotion** [comment]
I would have hoped we could do this. Clone the shit, deploy whatever is needed, open the editor on the correct exercise, let the guy do the thing then git reset --hard for the next guy

**Comment by primalmotion** [comment]
because the interview laptop right is like

maxresdefault

**Comment by Dogild** [comment]
Ideally we should have something like this

https://www.hackerrank.com/challenges/arrays-ds/problem

-- 
Alexandre Wilhelm

On October 18, 2017 at 12:02:06 PM, Antoine (notifications@github.com)
wrote:

because the interview laptop right is like

[image: maxresdefault]
<https://user-images.githubusercontent.com/208711/31737377-243417d8-b3fc-11e7-9ca1-675940e863ff.jpg>

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/aporeto-inc/interviews/pull/1#issuecomment-337694979>,
or mute the thread

**Comment by Dogild** [comment]
Any chance to give a solution on python/go ? Right now it would be impossible for me to give this exercise with the solution

**Pull request merged**
